version: '3.9'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
  server:
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    working_dir: /usr/src/app

volumes:
  dbdata:
    